# main.py

# --- All necessary imports ---
import os
import shutil
import json
import uuid
from fastapi import FastAPI, UploadFile, File
from api_models import *
from pdf_utils import extract_text_from_pdf
from ai_service import AIService
from dotenv import load_dotenv

# --- Create the FastAPI app instance ---
app = FastAPI()

# --- Load environment variables and initialize the AIService ---
load_dotenv()
ai_service = AIService(api_key=os.getenv("GOOGLE_API_KEY"))

# --- Add a constant for the temporary directory ---
TEMP_DIR = "temp"

# --- NEW: Simple in-memory cache for document text and chains ---
document_cache = {}


# --- The /process_pdf endpoint with full logic ---
@app.post("/process_pdf", response_model=ProcessPdfResponse)
async def process_pdf(file: UploadFile = File(...)):
    doc_id = str(uuid.uuid4())
    
    # Create a temporary directory if it doesn't exist
    if not os.path.exists(TEMP_DIR):
        os.makedirs(TEMP_DIR)
    
    # Define the path to save the uploaded PDF
    file_path = os.path.join(TEMP_DIR, f"{doc_id}_{file.filename}")
    
    # Save the uploaded file to the temporary path
    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
        
    # Use our utility to extract all the text from the PDF
    full_text = extract_text_from_pdf(file_path)
    print(f"Extracted {len(full_text)} characters from the PDF.")
    
    # Create the vector store "memory" for this document
    ai_service.create_vector_store_for_document(document_id=doc_id, text_content=full_text)
    
    # Store the text in our cache for the chat function later
    document_cache[doc_id] = {"text": full_text, "chain": None}

    # --- NEW: Generate structured modules using the AI ---
    print("Generating structured modules...")
    module_json_str = ai_service.generate_structured_modules(full_text)
    
    # It's safer to wrap JSON loading in a try-except block
    try:
        final_modules_data = json.loads(module_json_str)
    except json.JSONDecodeError:
        print("Error: Failed to parse JSON from AI response.")
        # Handle error, maybe return a default module structure
        final_modules_data = {"modules": []}

    # --- NEW: Add "Asset Awareness" to the structured modules ---
    # Make sure you have an assets.json file in this directory
    try:
        with open("assets.json") as f:
            assets = json.load(f)
        
        # Loop through the modules generated by the AI
        for module in final_modules_data.get("modules", []):
            combined_text = module.get('module_title', '') + " " + " ".join(module.get('lessons', []))
            module['has_ar'] = any(keyword.lower() in combined_text.lower() for keyword in assets if "model_url" in assets.get(keyword, {}))
            module['has_image'] = any(keyword.lower() in combined_text.lower() for keyword in assets if "image_url" in assets.get(keyword, {}))
    except FileNotFoundError:
        print("Warning: assets.json not found. Skipping asset awareness.")


    # Clean up the temporary file
    os.remove(file_path)

    return ProcessPdfResponse(document_id=doc_id, modules=final_modules_data.get("modules", []))


# --- The /chat endpoint remains the same for now ---
@app.post("/chat")
async def chat(request: ChatRequest):
    print(f"Received message for doc {request.document_id}: '{request.message}'")
    
    # This is a placeholder response for now
    return {"answer": "This is a dummy AI response."}